/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary": "#d7ffc5",
                "on-surface-variant": "#cfc4c5",
                "on-tertiary": "#003737",
                "background": "#131313",
                "on-secondary-fixed": "#022100",
                "outline": "#988e90",
                "error-container": "#93000a",
                "on-primary": "#303030",
                "surface-dim": "#131313",
                "on-secondary-fixed-variant": "#095300",
                "secondary-fixed-dim": "#2ae500",
                "on-background": "#e5e2e1",
                "surface-container-lowest": "#0e0e0e",
                "secondary-fixed": "#79ff5b",
                "error": "#ffb4ab",
                "on-secondary": "#053900",
                "outline-variant": "#4c4546",
                "secondary-container": "#2ff801",
                "tertiary-fixed": "#00fbfb",
                "inverse-surface": "#e5e2e1",
                "on-tertiary-container": "#008383",
                "on-error-container": "#ffdad6",
                "tertiary-container": "#000000",
                "surface-tint": "#c6c6c6",
                "surface-container-high": "#2a2a2a",
                "surface-container": "#201f1f",
                "on-secondary-container": "#0f6d00",
                "on-tertiary-fixed-variant": "#004f4f",
                "on-surface": "#e5e2e1",
                "on-primary-fixed": "#1b1b1b",
                "primary": "#c6c6c6",
                "surface-container-low": "#1c1b1b",
                "inverse-primary": "#5e5e5e",
                "surface": "#131313",
                "on-primary-fixed-variant": "#474747",
                "surface-variant": "#353534",
                "on-tertiary-fixed": "#002020",
                "primary-container": "#000000",
                "tertiary-fixed-dim": "#00dddd",
                "primary-fixed": "#e2e2e2",
                "on-error": "#690005",
                "inverse-on-surface": "#313030",
                "primary-fixed-dim": "#c6c6c6",
                "tertiary": "#00dddd",
                "surface-bright": "#393939",
                "on-primary-container": "#757575",
                "surface-container-highest": "#353534"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "lg": "48px",
                "xs": "4px",
                "md": "24px",
                "sm": "12px",
                "xl": "80px",
                "base": "8px",
                "gutter": "24px",
                "margin": "32px"
            },
            fontFamily: {
                "headline-lg-mobile": ["Geist"],
                "body-md": ["Geist"],
                "headline-lg": ["Geist"],
                "headline-xl": ["Geist"],
                "label-caps": ["Geist"],
                "body-sm": ["Geist"]
            },
            fontSize: {
                "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
                "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
                "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
                "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }]
            }
        },
    },
    plugins: [],
}